// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://foilfgdfbazigxtbikcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvaWxmZ2RmYmF6aWd4dGJpa2NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzE3MzIsImV4cCI6MjA1OTYwNzczMn0.ygVtge6hqaAP5J3neQoyeQoOu26uPDjgGvIj1-zmpVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);